/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.0.9 -K --shadows -D display2.gltf
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Display2(props) {
  const { nodes, materials } = useGLTF('/display2.gltf')
  return (
    <group {...props} dispose={null}>
      <group>
        <group position={[0.79, 0.51, -0.84]} rotation={[-1.87, -Math.PI / 2, 0]} scale={[0.02, 0.02, 0.03]}>
          <group position={[-13.55, -0.14, 0]}>
            <mesh castShadow receiveShadow geometry={nodes.Veshalka001.geometry} material={nodes.Veshalka001.material} position={[0.42, -0.05, 3.14]} rotation={[1.56, 0.95, -1.56]} scale={-0.09} />
            <mesh castShadow receiveShadow geometry={nodes.Wheel002.geometry} material={nodes.Wheel002.material} position={[0.6, -0.41, 3.37]} rotation={[Math.PI / 2, 0, -Math.PI]} scale={-1} />
            <mesh castShadow receiveShadow geometry={nodes.Wheel003.geometry} material={nodes.Wheel003.material} position={[0.6, -0.41, -3.37]} rotation={[-Math.PI / 2, 0, 0]} />
          </group>
          <group position={[14.49, -0.14, 0]}>
            <mesh castShadow receiveShadow geometry={nodes.Veshalka.geometry} material={nodes.Veshalka.material} position={[-0.42, -0.09, 3.14]} rotation={[-1.58, 0.95, -1.56]} scale={0.09} />
            <mesh castShadow receiveShadow geometry={nodes.Wheel.geometry} material={nodes.Wheel.material} position={[-0.6, -0.41, -3.37]} rotation={[Math.PI / 2, 0, 0]} scale={-1} />
            <mesh castShadow receiveShadow geometry={nodes.Wheel001.geometry} material={nodes.Wheel001.material} position={[-0.6, -0.41, 3.37]} rotation={[-Math.PI / 2, 0, Math.PI]} />
          </group>
          <mesh castShadow receiveShadow geometry={nodes.Line001.geometry} material={nodes.Line001.material} position={[-0.6, 1.74, -1.7]} />
          <mesh castShadow receiveShadow geometry={nodes.Line001001.geometry} material={nodes.Line001001.material} position={[-0.6, 1.74, -1.7]} />
        </group>
        <group position={[-2.8, 0.14, 2.46]} rotation={[0, 1.53, 0]} scale={[0.02, 0.02, 0.03]}>
          <group position={[-13.55, -0.14, 0]}>
            <mesh castShadow receiveShadow geometry={nodes.Veshalka001001.geometry} material={nodes.Veshalka001001.material} position={[0.42, -0.05, 3.14]} rotation={[1.56, 0.95, -1.56]} scale={-0.09} />
            <mesh castShadow receiveShadow geometry={nodes.Wheel002001.geometry} material={nodes.Wheel002001.material} position={[0.6, -0.41, 3.37]} rotation={[Math.PI / 2, 0, -Math.PI]} scale={-1} />
            <mesh castShadow receiveShadow geometry={nodes.Wheel003001.geometry} material={nodes.Wheel003001.material} position={[0.6, -0.41, -3.37]} rotation={[-Math.PI / 2, 0, 0]} />
          </group>
          <group position={[14.49, -0.14, 0]}>
            <mesh castShadow receiveShadow geometry={nodes.Veshalka001_1.geometry} material={nodes.Veshalka001_1.material} position={[-0.42, -0.09, 3.14]} rotation={[-1.58, 0.95, -1.56]} scale={0.09} />
            <mesh castShadow receiveShadow geometry={nodes.Wheel001_1.geometry} material={nodes.Wheel001_1.material} position={[-0.6, -0.41, -3.37]} rotation={[Math.PI / 2, 0, 0]} scale={-1} />
            <mesh castShadow receiveShadow geometry={nodes.Wheel001001.geometry} material={nodes.Wheel001001.material} position={[-0.6, -0.41, 3.37]} rotation={[-Math.PI / 2, 0, Math.PI]} />
          </group>
          <mesh castShadow receiveShadow geometry={nodes.Line001002.geometry} material={nodes.Line001002.material} position={[-0.6, 1.74, -1.7]} />
          <mesh castShadow receiveShadow geometry={nodes.Line001003.geometry} material={nodes.Line001003.material} position={[-0.6, 1.74, -1.7]} />
        </group>
        <group position={[2.31, 0.34, -2.37]} rotation={[-Math.PI / 2, 0, 0]}>
          <group position={[-0.43, 0.22, 0]} rotation={[Math.PI / 2, 0, 0]}>
            <group>
              <group>
                <mesh castShadow receiveShadow geometry={nodes.Tool_box1_Tool_box_plastic_0.geometry} material={nodes.Tool_box1_Tool_box_plastic_0.material} position={[0.25, -0.11, 0.11]} scale={0.53} />
                <mesh castShadow receiveShadow geometry={nodes.Tool_box1_Tool_box_polymer_0.geometry} material={nodes.Tool_box1_Tool_box_polymer_0.material} position={[0.25, -0.11, 0.11]} scale={0.53} />
              </group>
            </group>
          </group>
        </group>
        <group position={[1.43, 0.25, -2.37]} rotation={[-Math.PI, 0, 0]} scale={[0.02, 0.02, 0.03]}>
          <group position={[-13.55, -0.14, 0]}>
            <mesh castShadow receiveShadow geometry={nodes.Veshalka001002.geometry} material={nodes.Veshalka001002.material} position={[0.42, -0.05, 3.14]} rotation={[1.56, 0.95, -1.56]} scale={-0.09} />
            <mesh castShadow receiveShadow geometry={nodes.Wheel002002.geometry} material={nodes.Wheel002002.material} position={[0.6, -0.41, 3.37]} rotation={[Math.PI / 2, 0, -Math.PI]} scale={-1} />
            <mesh castShadow receiveShadow geometry={nodes.Wheel003002.geometry} material={nodes.Wheel003002.material} position={[0.6, -0.41, -3.37]} rotation={[-Math.PI / 2, 0, 0]} />
          </group>
          <group position={[14.49, -0.14, 0]}>
            <mesh castShadow receiveShadow geometry={nodes.Veshalka002.geometry} material={nodes.Veshalka002.material} position={[-0.42, -0.09, 3.14]} rotation={[-1.58, 0.95, -1.56]} scale={0.09} />
            <mesh castShadow receiveShadow geometry={nodes.Wheel002_1.geometry} material={nodes.Wheel002_1.material} position={[-0.6, -0.41, -3.37]} rotation={[Math.PI / 2, 0, 0]} scale={-1} />
            <mesh castShadow receiveShadow geometry={nodes.Wheel001002.geometry} material={nodes.Wheel001002.material} position={[-0.6, -0.41, 3.37]} rotation={[-Math.PI / 2, 0, Math.PI]} />
          </group>
          <mesh castShadow receiveShadow geometry={nodes.Line001004.geometry} material={nodes.Line001004.material} position={[-0.6, 1.74, -1.7]} />
          <mesh castShadow receiveShadow geometry={nodes.Line001005.geometry} material={nodes.Line001005.material} position={[-0.6, 1.74, -1.7]} />
        </group>
        <group position={[-0.5, 2.49, -2.84]} rotation={[-Math.PI / 2, 0, 0]} scale={0}>
          <group rotation={[Math.PI / 2, 0, 0]}>
            <group>
              <group position={[0, 394.08, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh castShadow receiveShadow geometry={nodes.Cube_Black_base_0.geometry} material={nodes.Cube_Black_base_0.material} />
              </group>
              <group position={[-1095.86, 394.08, 19.07]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh castShadow receiveShadow geometry={nodes.Cube001_Black_base_0.geometry} material={nodes.Cube001_Black_base_0.material} />
              </group>
              <group position={[0, 394.08, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh castShadow receiveShadow geometry={nodes.Cube002_Black_base_0.geometry} material={nodes.Cube002_Black_base_0.material} />
              </group>
              <group position={[0, 800.44, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={[100, 100, 122.72]}>
                <mesh castShadow receiveShadow geometry={nodes.Cube003_White_metal_0.geometry} material={nodes.Cube003_White_metal_0.material} />
              </group>
              <group position={[0, 680.51, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh castShadow receiveShadow geometry={nodes.Cube004_Black_base_table_0.geometry} material={nodes.Cube004_Black_base_table_0.material} />
              </group>
              <group position={[0, 311.13, 1222.32]} rotation={[1.14, 0, -Math.PI]} scale={[-220.51, -10.58, -139.84]}>
                <mesh castShadow receiveShadow geometry={nodes.Cube008_White_metal_0.geometry} material={nodes.Cube008_White_metal_0.material} />
              </group>
              <group position={[0, 800.44, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh castShadow receiveShadow geometry={nodes.Cube009_Black_base_0.geometry} material={nodes.Cube009_Black_base_0.material} />
              </group>
              <group position={[973.79, 2313.21, -334.72]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={[27.18, 24.45, 43.57]}>
                <group position={[-0.04, 0, 1.95]} rotation={[0, 0, -Math.PI / 2]} scale={[4.09, 3.68, 2.3]}>
                  <mesh castShadow receiveShadow geometry={nodes.Cube013_White_metal_boxes_0.geometry} material={nodes.Cube013_White_metal_boxes_0.material} />
                </group>
              </group>
              <group position={[-1.66, 2355.13, -307.24]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh castShadow receiveShadow geometry={nodes.Cube017_Black_base_0.geometry} material={nodes.Cube017_Black_base_0.material} />
              </group>
              <group position={[0, 680.51, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh castShadow receiveShadow geometry={nodes.Cylinder_Shiny_metal_gold001_0.geometry} material={nodes.Cylinder_Shiny_metal_gold001_0.material} />
              </group>
              <group position={[403.26, 603.37, -1136.55]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh castShadow receiveShadow geometry={nodes.Cylinder001_Black_base_0.geometry} material={nodes.Cylinder001_Black_base_0.material} />
              </group>
              <group position={[-402.13, 603.37, -1136.55]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh castShadow receiveShadow geometry={nodes.Cylinder002_Black_base_0.geometry} material={nodes.Cylinder002_Black_base_0.material} />
              </group>
              <group position={[403.26, 584.83, -48.56]} rotation={[-Math.PI / 2, 0, 0]} scale={[100, 99.88, 100]}>
                <mesh castShadow receiveShadow geometry={nodes.Cylinder003_Shiny_metal_0.geometry} material={nodes.Cylinder003_Shiny_metal_0.material} />
              </group>
              <group position={[-402.13, 584.83, -48.56]} rotation={[-Math.PI / 2, 0, 0]} scale={[100, 99.88, 100]}>
                <mesh castShadow receiveShadow geometry={nodes.Cylinder004_Shiny_metal_0.geometry} material={nodes.Cylinder004_Shiny_metal_0.material} />
              </group>
              <group position={[403.26, 619.3, -48.56]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh castShadow receiveShadow geometry={nodes.Cylinder005_Black_base_0.geometry} material={nodes.Cylinder005_Black_base_0.material} />
              </group>
              <group position={[-0.02, 508.83, 858.87]} rotation={[-Math.PI / 2, 0, 0]} scale={[29.21, 29.21, 14.98]}>
                <mesh castShadow receiveShadow geometry={nodes.Cylinder010_Black_base_0.geometry} material={nodes.Cylinder010_Black_base_0.material} />
              </group>
              <group position={[-0.02, 582.29, -919.06]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh castShadow receiveShadow geometry={nodes.Cylinder012_White_metal_0.geometry} material={nodes.Cylinder012_White_metal_0.material} />
              </group>
              <group position={[-0.02, 525.42, -919.06]} rotation={[-Math.PI / 2, 0, 0]} scale={129.5}>
                <mesh castShadow receiveShadow geometry={nodes.Cylinder014_Black_base_0.geometry} material={nodes.Cylinder014_Black_base_0.material} />
              </group>
              <group position={[-0.02, 559.49, -919.06]} rotation={[-Math.PI / 2, 0, 0]} scale={[130.19, 130.19, 107.5]}>
                <mesh castShadow receiveShadow geometry={nodes.Cylinder017_Black_resin_0.geometry} material={nodes.Cylinder017_Black_resin_0.material} />
              </group>
              <group position={[0, 800.44, -47.44]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh castShadow receiveShadow geometry={nodes.Cylinder020_White_metal_0.geometry} material={nodes.Cylinder020_White_metal_0.material} />
              </group>
              <group position={[0, 800.44, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh castShadow receiveShadow geometry={nodes.Cylinder022_Shiny_metal_0.geometry} material={nodes.Cylinder022_Shiny_metal_0.material} />
              </group>
              <group position={[-1.66, 2300.07, -100.91]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={[89.02, 83.15, 89.02]}>
                <mesh castShadow receiveShadow geometry={nodes.Cylinder023_Shiny_metal_0.geometry} material={nodes.Cylinder023_Shiny_metal_0.material} />
              </group>
              <group position={[-1.66, 2494.43, -100.91]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={[89.83, 81.52, 89.83]}>
                <mesh castShadow receiveShadow geometry={nodes.Cylinder024_Shiny_metal_0.geometry} material={nodes.Cylinder024_Shiny_metal_0.material} />
              </group>
            </group>
          </group>
        </group>
        <group position={[-0.3, 2.24, -2.67]} rotation={[-Math.PI / 2, 0, 0]}>
          <group position={[-0.43, 0.22, 0]} rotation={[Math.PI / 2, 0, 0]}>
            <group>
              <group>
                <mesh castShadow receiveShadow geometry={nodes.Tool_box1_Tool_box_plastic_0001.geometry} material={nodes.Tool_box1_Tool_box_plastic_0001.material} position={[0.25, -0.11, 0.11]} scale={0.53} />
                <mesh castShadow receiveShadow geometry={nodes.Tool_box1_Tool_box_polymer_0001.geometry} material={nodes.Tool_box1_Tool_box_polymer_0001.material} position={[0.25, -0.11, 0.19]} scale={0.53} />
                <mesh castShadow receiveShadow geometry={nodes.Tool_box1_Tool_box_polymer_0002.geometry} material={nodes.Tool_box1_Tool_box_polymer_0002.material} position={[-1.55, -0.11, 2.17]} scale={0.53} />
              </group>
            </group>
          </group>
        </group>
        <group position={[0.32, 2.55, -2.73]} rotation={[-Math.PI, 0.61, -Math.PI]} scale={0}>
          <group position={[-16.99, -21.73, 11.93]} rotation={[-Math.PI / 2, 0, -0.96]} scale={-9.98}>
            <mesh castShadow receiveShadow geometry={nodes.Mesh022.geometry} material={materials['monitor_plastic.002']} />
            <mesh castShadow receiveShadow geometry={nodes.Mesh022_1.geometry} material={materials['gray_plastic.001']} />
            <mesh castShadow receiveShadow geometry={nodes.Mesh022_2.geometry} material={materials['keyboard.002']} />
            <mesh castShadow receiveShadow geometry={nodes.Mesh022_3.geometry} material={materials['sensor.001']} />
            <mesh castShadow receiveShadow geometry={nodes.Mesh022_4.geometry} material={materials['socket_USB.001']} />
            <mesh castShadow receiveShadow geometry={nodes.Mesh022_5.geometry} material={materials['socket_power.001']} />
            <mesh castShadow receiveShadow geometry={nodes.Mesh022_6.geometry} material={materials['socket_steel.001']} />
            <mesh castShadow receiveShadow geometry={nodes.Mesh022_7.geometry} material={materials['headphones.001']} />
            <mesh castShadow receiveShadow geometry={nodes.Mesh022_8.geometry} material={materials['logo.001']} />
          </group>
          <group position={[47.66, 64.58, 72.96]} rotation={[-2.72, -0.57, -2.91]} scale={9.98}>
            <mesh castShadow receiveShadow geometry={nodes.Mesh023.geometry} material={materials['gray_plastic.001']} />
            <mesh castShadow receiveShadow geometry={nodes.Mesh023_1.geometry} material={materials['display.001']} />
            <mesh castShadow receiveShadow geometry={nodes.Mesh023_2.geometry} material={materials['monitor_plastic.004']} />
            <mesh castShadow receiveShadow geometry={nodes.Mesh023_3.geometry} material={materials['logo_monitor_bottom.003']} />
          </group>
        </group>
        <group position={[-2.3, 2.49, -0.85]} rotation={[-Math.PI / 2, 0, 0]} scale={0}>
          <group rotation={[Math.PI / 2, 0, 0]}>
            <group>
              <group position={[0, 394.08, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh castShadow receiveShadow geometry={nodes.Cube_Black_base_0001.geometry} material={nodes.Cube_Black_base_0001.material} />
              </group>
              <group position={[-1095.86, 394.08, 19.07]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh castShadow receiveShadow geometry={nodes.Cube001_Black_base_0001.geometry} material={nodes.Cube001_Black_base_0001.material} />
              </group>
              <group position={[0, 394.08, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh castShadow receiveShadow geometry={nodes.Cube002_Black_base_0001.geometry} material={nodes.Cube002_Black_base_0001.material} />
              </group>
              <group position={[0, 800.44, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={[100, 100, 122.72]}>
                <mesh castShadow receiveShadow geometry={nodes.Cube003_White_metal_0001.geometry} material={nodes.Cube003_White_metal_0001.material} />
              </group>
              <group position={[0, 680.51, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh castShadow receiveShadow geometry={nodes.Cube004_Black_base_table_0001.geometry} material={nodes.Cube004_Black_base_table_0001.material} />
              </group>
              <group position={[0, 311.13, 1222.32]} rotation={[1.14, 0, -Math.PI]} scale={[-220.51, -10.58, -139.84]}>
                <mesh castShadow receiveShadow geometry={nodes.Cube008_White_metal_0001.geometry} material={nodes.Cube008_White_metal_0001.material} />
              </group>
              <group position={[0, 800.44, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh castShadow receiveShadow geometry={nodes.Cube009_Black_base_0001.geometry} material={nodes.Cube009_Black_base_0001.material} />
              </group>
              <group position={[973.79, 2313.21, -334.72]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={[27.18, 24.45, 43.57]}>
                <group position={[-0.04, 0, 1.95]} rotation={[0, 0, -Math.PI / 2]} scale={[4.09, 3.68, 2.3]}>
                  <mesh castShadow receiveShadow geometry={nodes.Cube013_White_metal_boxes_0001.geometry} material={nodes.Cube013_White_metal_boxes_0001.material} />
                </group>
              </group>
              <group position={[-1.66, 2355.13, -307.24]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh castShadow receiveShadow geometry={nodes.Cube017_Black_base_0001.geometry} material={nodes.Cube017_Black_base_0001.material} />
              </group>
              <group position={[0, 680.51, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh castShadow receiveShadow geometry={nodes.Cylinder_Shiny_metal_gold001_0001.geometry} material={nodes.Cylinder_Shiny_metal_gold001_0001.material} />
              </group>
              <group position={[403.26, 603.37, -1136.55]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh castShadow receiveShadow geometry={nodes.Cylinder001_Black_base_0001.geometry} material={nodes.Cylinder001_Black_base_0001.material} />
              </group>
              <group position={[-402.13, 603.37, -1136.55]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh castShadow receiveShadow geometry={nodes.Cylinder002_Black_base_0001.geometry} material={nodes.Cylinder002_Black_base_0001.material} />
              </group>
              <group position={[403.26, 584.83, -48.56]} rotation={[-Math.PI / 2, 0, 0]} scale={[100, 99.88, 100]}>
                <mesh castShadow receiveShadow geometry={nodes.Cylinder003_Shiny_metal_0001.geometry} material={nodes.Cylinder003_Shiny_metal_0001.material} />
              </group>
              <group position={[-402.13, 584.83, -48.56]} rotation={[-Math.PI / 2, 0, 0]} scale={[100, 99.88, 100]}>
                <mesh castShadow receiveShadow geometry={nodes.Cylinder004_Shiny_metal_0001.geometry} material={nodes.Cylinder004_Shiny_metal_0001.material} />
              </group>
              <group position={[403.26, 619.3, -48.56]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh castShadow receiveShadow geometry={nodes.Cylinder005_Black_base_0001.geometry} material={nodes.Cylinder005_Black_base_0001.material} />
              </group>
              <group position={[-0.02, 508.83, 858.87]} rotation={[-Math.PI / 2, 0, 0]} scale={[29.21, 29.21, 14.98]}>
                <mesh castShadow receiveShadow geometry={nodes.Cylinder010_Black_base_0001.geometry} material={nodes.Cylinder010_Black_base_0001.material} />
              </group>
              <group position={[-0.02, 582.29, -919.06]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh castShadow receiveShadow geometry={nodes.Cylinder012_White_metal_0001.geometry} material={nodes.Cylinder012_White_metal_0001.material} />
              </group>
              <group position={[-0.02, 525.42, -919.06]} rotation={[-Math.PI / 2, 0, 0]} scale={129.5}>
                <mesh castShadow receiveShadow geometry={nodes.Cylinder014_Black_base_0001.geometry} material={nodes.Cylinder014_Black_base_0001.material} />
              </group>
              <group position={[-0.02, 559.49, -919.06]} rotation={[-Math.PI / 2, 0, 0]} scale={[130.19, 130.19, 107.5]}>
                <mesh castShadow receiveShadow geometry={nodes.Cylinder017_Black_resin_0001.geometry} material={nodes.Cylinder017_Black_resin_0001.material} />
              </group>
              <group position={[0, 800.44, -47.44]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh castShadow receiveShadow geometry={nodes.Cylinder020_White_metal_0001.geometry} material={nodes.Cylinder020_White_metal_0001.material} />
              </group>
              <group position={[0, 800.44, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh castShadow receiveShadow geometry={nodes.Cylinder022_Shiny_metal_0001.geometry} material={nodes.Cylinder022_Shiny_metal_0001.material} />
              </group>
              <group position={[-1.66, 2300.07, -100.91]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={[89.02, 83.15, 89.02]}>
                <mesh castShadow receiveShadow geometry={nodes.Cylinder023_Shiny_metal_0001.geometry} material={nodes.Cylinder023_Shiny_metal_0001.material} />
              </group>
              <group position={[-1.66, 2494.43, -100.91]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={[89.83, 81.52, 89.83]}>
                <mesh castShadow receiveShadow geometry={nodes.Cylinder024_Shiny_metal_0001.geometry} material={nodes.Cylinder024_Shiny_metal_0001.material} />
              </group>
            </group>
          </group>
        </group>
        <group position={[-1.86, 2.55, -0.77]} rotation={[-Math.PI, 0.61, -Math.PI]} scale={0}>
          <group position={[-16.99, -21.73, 11.93]} rotation={[-Math.PI / 2, 0, -0.96]} scale={-9.98}>
            <mesh castShadow receiveShadow geometry={nodes.Mesh027.geometry} material={materials['monitor_plastic.002']} />
            <mesh castShadow receiveShadow geometry={nodes.Mesh027_1.geometry} material={materials['gray_plastic.001']} />
            <mesh castShadow receiveShadow geometry={nodes.Mesh027_2.geometry} material={materials['keyboard.002']} />
            <mesh castShadow receiveShadow geometry={nodes.Mesh027_3.geometry} material={materials['sensor.001']} />
            <mesh castShadow receiveShadow geometry={nodes.Mesh027_4.geometry} material={materials['socket_USB.001']} />
            <mesh castShadow receiveShadow geometry={nodes.Mesh027_5.geometry} material={materials['socket_power.001']} />
            <mesh castShadow receiveShadow geometry={nodes.Mesh027_6.geometry} material={materials['socket_steel.001']} />
            <mesh castShadow receiveShadow geometry={nodes.Mesh027_7.geometry} material={materials['headphones.001']} />
            <mesh castShadow receiveShadow geometry={nodes.Mesh027_8.geometry} material={materials['logo.001']} />
          </group>
          <group position={[47.66, 64.58, 72.96]} rotation={[-2.72, -0.57, -2.91]} scale={9.98}>
            <mesh castShadow receiveShadow geometry={nodes.Mesh028.geometry} material={materials['gray_plastic.001']} />
            <mesh castShadow receiveShadow geometry={nodes.Mesh028_1.geometry} material={materials['display.001']} />
            <mesh castShadow receiveShadow geometry={nodes.Mesh028_2.geometry} material={materials['monitor_plastic.004']} />
            <mesh castShadow receiveShadow geometry={nodes.Mesh028_3.geometry} material={materials['logo_monitor_bottom.003']} />
          </group>
        </group>
        <group position={[-1.4, 2.55, 0.62]} rotation={[-Math.PI / 2, 0, 0]} scale={0.04}>
          <group>
            <mesh castShadow receiveShadow geometry={nodes.Object_2.geometry} material={materials['20221231_1431271384153216']} />
            <mesh castShadow receiveShadow geometry={nodes.Object_3.geometry} material={materials['20221231_143201']} />
            <mesh castShadow receiveShadow geometry={nodes.Object_4.geometry} material={materials['20221231_1432011']} />
            <mesh castShadow receiveShadow geometry={nodes.Object_5.geometry} material={materials['20221231_143220']} />
            <mesh castShadow receiveShadow geometry={nodes.Object_6.geometry} material={materials['20221231_1432201']} />
          </group>
        </group>
        <mesh castShadow receiveShadow geometry={nodes.Perfil2020.geometry} material={nodes.Perfil2020.material} position={[-1.97, 0.12, 1.62]} rotation={[Math.PI / 2, 0, 0.37]} scale={0} />
        <mesh castShadow receiveShadow geometry={nodes.Perfil2020001.geometry} material={nodes.Perfil2020001.material} position={[-1.69, 0.14, 1.69]} rotation={[1.57, -0.08, 1.57]} scale={0} />
        <mesh castShadow receiveShadow geometry={nodes.Perfil2020002.geometry} material={nodes.Perfil2020002.material} position={[-2.18, 0.1, 2.02]} rotation={[Math.PI / 2, 0, 0]} scale={0} />
        <mesh castShadow receiveShadow geometry={nodes.Perfil2020003.geometry} material={nodes.Perfil2020003.material} position={[-1.97, 0.61, 1.23]} rotation={[Math.PI / 2, 0, 2]} scale={0} />
        <mesh castShadow receiveShadow geometry={nodes.suportShula.geometry} material={nodes.suportShula.material} position={[1.07, 0.94, -1.17]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.02} />
        <mesh castShadow receiveShadow geometry={nodes.suportShula001.geometry} material={nodes.suportShula001.material} position={[1.07, 0.94, -1.45]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.02} />
        <mesh castShadow receiveShadow geometry={nodes.Perfil2020004.geometry} material={nodes.Perfil2020004.material} position={[1.41, 0.99, -2.36]} rotation={[Math.PI / 2, 0, -1.88]} scale={0} />
        <mesh castShadow receiveShadow geometry={nodes.Perfil2020005.geometry} material={nodes.Perfil2020005.material} position={[1.52, 1.02, -2.36]} rotation={[Math.PI / 2, -0.14, -Math.PI / 2]} scale={0} />
        <mesh castShadow receiveShadow geometry={nodes.Perfil2020006.geometry} material={nodes.Perfil2020006.material} position={[1.17, 0.74, -1.7]} rotation={[Math.PI / 2, 0, 2.65]} scale={0} />
        <mesh castShadow receiveShadow geometry={nodes.Perfil2020007.geometry} material={nodes.Perfil2020007.material} position={[-0.86, 2.86, -1.59]} rotation={[Math.PI / 2, 0, 0.13]} scale={0} />
        <mesh castShadow receiveShadow geometry={nodes.Perfil2020008.geometry} material={nodes.Perfil2020008.material} position={[-0.76, 2.86, -1.55]} rotation={[Math.PI / 2, 0, 0]} scale={0} />
        <mesh castShadow receiveShadow geometry={nodes.Perfil2020009.geometry} material={nodes.Perfil2020009.material} position={[-0.71, 2.86, -1.62]} rotation={[Math.PI / 2, 0, 0]} scale={0} />
        <mesh castShadow receiveShadow geometry={nodes.Perfil2020010.geometry} material={nodes.Perfil2020010.material} position={[-0.79, 2.9, -1.52]} rotation={[Math.PI / 2, 0, 2.65]} scale={0} />
        <mesh castShadow receiveShadow geometry={nodes.Perfil2020011.geometry} material={nodes.Perfil2020011.material} position={[-0.79, 2.9, -1.83]} rotation={[Math.PI / 2, 0, -0.85]} scale={0} />
        <mesh castShadow receiveShadow geometry={nodes.Perfil2020012.geometry} material={nodes.Perfil2020012.material} position={[-0.79, 2.95, -1.68]} rotation={[Math.PI / 2, 0, -Math.PI / 9]} scale={0} />
        <mesh castShadow receiveShadow geometry={nodes.Router.geometry} material={nodes.Router.material} position={[0.79, 2.54, -2.86]} rotation={[Math.PI / 2, 0, 0.25]} scale={0.01} />
        <mesh castShadow receiveShadow geometry={nodes.Monroe_L160.geometry} material={nodes.Monroe_L160.material} position={[0.49, 2.26, -1.47]} rotation={[0, -0.25, 0]} scale={0} />
        <mesh castShadow receiveShadow geometry={nodes.Cube011.geometry} material={nodes.Cube011.material} position={[0.41, 3.09, -2.91]} scale={[0.4, 0.02, 0.09]} />
        <mesh castShadow receiveShadow geometry={nodes.robofeu.geometry} material={nodes.robofeu.material} position={[0.2, 3.11, -2.91]} rotation={[0, 1.53, 0]} scale={0} />
        <mesh castShadow receiveShadow geometry={nodes.robofeu001.geometry} material={nodes.robofeu001.material} position={[0.67, 3.11, -2.91]} rotation={[-Math.PI, 1.22, -Math.PI]} scale={0} />
        <group position={[-0.04, 2.78, -2.69]} rotation={[0, -1.2, 0]} scale={0.34}>
          <mesh castShadow receiveShadow geometry={nodes.Cylinder002.geometry} material={materials.metal} />
          <mesh castShadow receiveShadow geometry={nodes.Cylinder002_1.geometry} material={materials['window glass']} />
          <mesh castShadow receiveShadow geometry={nodes.Cylinder002_2.geometry} material={materials.red} />
          <mesh castShadow receiveShadow geometry={nodes.Cylinder002_3.geometry} material={materials.white} />
          <mesh castShadow receiveShadow geometry={nodes.Cylinder002_4.geometry} material={materials['white.Smoke']} />
        </group>
        <mesh castShadow receiveShadow geometry={nodes.Monroe_L160001.geometry} material={nodes.Monroe_L160001.material} position={[-1.46, 2.26, 0.59]} rotation={[0, -0.25, 0]} scale={0} />
        <mesh castShadow receiveShadow geometry={nodes.Cube029.geometry} material={nodes.Cube029.material} position={[-2.91, 3.22, 0.51]} rotation={[0, 1.57, 0]} scale={[0.4, 0.02, 0.09]} />
        <mesh castShadow receiveShadow geometry={nodes.robofeu002.geometry} material={nodes.robofeu002.material} position={[-2.91, 3.24, 0.83]} rotation={[-Math.PI, 0.04, -Math.PI]} scale={0} />
        <mesh castShadow receiveShadow geometry={nodes.robofeu003.geometry} material={nodes.robofeu003.material} position={[-2.91, 3.24, 0.17]} rotation={[-Math.PI, 0.38, -Math.PI]} scale={0} />
        <group position={[-2.85, 3.51, 0.5]} rotation={[0, -0.14, 0]} scale={0.34}>
          <mesh castShadow receiveShadow geometry={nodes.Cylinder005.geometry} material={materials.metal} />
          <mesh castShadow receiveShadow geometry={nodes.Cylinder005_1.geometry} material={materials['window glass']} />
          <mesh castShadow receiveShadow geometry={nodes.Cylinder005_2.geometry} material={materials.red} />
          <mesh castShadow receiveShadow geometry={nodes.Cylinder005_3.geometry} material={materials.white} />
          <mesh castShadow receiveShadow geometry={nodes.Cylinder005_4.geometry} material={materials['white.Smoke']} />
        </group>
        <mesh castShadow receiveShadow geometry={nodes.Perfil2020013.geometry} material={nodes.Perfil2020013.material} position={[-2.24, 2.02, 0.55]} rotation={[Math.PI / 2, 0, -0.49]} scale={0} />
        <mesh castShadow receiveShadow geometry={nodes.Perfil2020014.geometry} material={nodes.Perfil2020014.material} position={[-2.13, 2.02, 0.51]} rotation={[Math.PI / 2, 0, -0.62]} scale={0} />
        <mesh castShadow receiveShadow geometry={nodes.Perfil2020015.geometry} material={nodes.Perfil2020015.material} position={[-2.13, 2.02, 0.43]} rotation={[Math.PI / 2, 0, -0.62]} scale={0} />
        <mesh castShadow receiveShadow geometry={nodes.Perfil2020016.geometry} material={nodes.Perfil2020016.material} position={[-2.14, 2.06, 0.56]} rotation={[Math.PI / 2, 0, 2.03]} scale={0} />
        <mesh castShadow receiveShadow geometry={nodes.Perfil2020017.geometry} material={nodes.Perfil2020017.material} position={[-2.32, 2.06, 0.31]} rotation={[Math.PI / 2, 0, -1.48]} scale={0} />
        <mesh castShadow receiveShadow geometry={nodes.Perfil2020018.geometry} material={nodes.Perfil2020018.material} position={[-2.23, 2.11, 0.43]} rotation={[Math.PI / 2, 0, -0.97]} scale={0} />
        <mesh castShadow receiveShadow geometry={nodes.Perfil2020019.geometry} material={nodes.Perfil2020019.material} position={[-1.37, 2.3, -0.66]} rotation={[Math.PI / 2, 0, -1.44]} scale={0} />
        <mesh castShadow receiveShadow geometry={nodes.Perfil2020020.geometry} material={nodes.Perfil2020020.material} position={[-1.34, 2.3, -0.76]} rotation={[Math.PI / 2, 0, -1.58]} scale={0} />
        <mesh castShadow receiveShadow geometry={nodes.Perfil2020021.geometry} material={nodes.Perfil2020021.material} position={[-1.31, 2.34, -0.73]} rotation={[Math.PI / 2, 0, 1.08]} scale={0} />
        <mesh castShadow receiveShadow geometry={nodes.Router001.geometry} material={nodes.Router001.material} position={[-1.4, 2.54, -0.89]} rotation={[Math.PI / 2, 0, 0.25]} scale={0.01} />
        <mesh castShadow receiveShadow geometry={nodes.Cube001.geometry} material={nodes.Cube001.material} position={[0, 0.08, 0]} scale={[1, 0.03, 1]} />
        <mesh castShadow receiveShadow geometry={nodes.Cube004.geometry} material={nodes.Cube004.material} position={[0, 1, -2]} />
        <mesh castShadow receiveShadow geometry={nodes.Cube005.geometry} material={nodes.Cube005.material} position={[-2, 2, -2]} scale={[1, 2, 1]} />
        <mesh castShadow receiveShadow geometry={nodes.Cube006.geometry} material={nodes.Cube006.material} position={[0, 2, -3.09]} rotation={[0, Math.PI / 2, 0]} scale={[0.1, 2, 1]} />
        <mesh castShadow receiveShadow geometry={nodes.Cube008.geometry} material={nodes.Cube008.material} position={[-3.1, 3, -2]} scale={[0.1, 3, 1]} />
        <mesh castShadow receiveShadow geometry={nodes.Cube012.geometry} material={nodes.Cube012.material} position={[-2, 1, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.Cube013.geometry} material={nodes.Cube013.material} position={[-2, 3, -3.09]} rotation={[0, Math.PI / 2, 0]} scale={[0.1, 3, 1]} />
        <mesh castShadow receiveShadow geometry={nodes.Cube014.geometry} material={nodes.Cube014.material} position={[-3.1, 2, 0]} scale={[0.1, 2, 1]} />
        <mesh castShadow receiveShadow geometry={nodes.Cube017.geometry} material={nodes.Cube017.material} position={[2, 0.07, -2]} scale={[1, 0.03, 1]} />
        <mesh castShadow receiveShadow geometry={nodes.Cube018.geometry} material={nodes.Cube018.material} position={[-2, 0.07, 2]} scale={[1, 0.03, 1]} />
        <mesh castShadow receiveShadow geometry={nodes.Cube019.geometry} material={nodes.Cube019.material} position={[-3.1, 1, 2]} scale={[0.1, 1, 1]} />
        <mesh castShadow receiveShadow geometry={nodes.Cube021.geometry} material={nodes.Cube021.material} position={[2, 1, -3.09]} rotation={[0, Math.PI / 2, 0]} scale={[0.1, 1, 1]} />
        <mesh castShadow receiveShadow geometry={nodes.Cube010.geometry} material={nodes.Cube010.material} position={[1.09, 1, -2.8]} rotation={[0, -Math.PI / 2, 0]} scale={[0.2, 1, 0.1]} />
        <mesh castShadow receiveShadow geometry={nodes.Cube015.geometry} material={nodes.Cube015.material} position={[-2.8, 3, -0.9]} rotation={[Math.PI, 0, Math.PI]} scale={[0.2, 1, 0.1]} />
        <mesh castShadow receiveShadow geometry={nodes.Cube022.geometry} material={nodes.Cube022.material} position={[-0.85, 0.78, 0.16]} rotation={[-1.07, 0.35, 1.5]} scale={0.33} />
        <mesh castShadow receiveShadow geometry={nodes['tool-rack001'].geometry} material={nodes['tool-rack001'].material} position={[-0.92, 0.73, 0.17]} rotation={[0, Math.PI / 2, 0]} scale={0} />
        <mesh castShadow receiveShadow geometry={nodes.surusurubelnita001.geometry} material={nodes.surusurubelnita001.material} position={[-0.76, 0.96, -0.62]} rotation={[0.07, 0.62, 1.44]} scale={1.06} />
        <mesh castShadow receiveShadow geometry={nodes.bench_vice_01_1k001.geometry} material={nodes.bench_vice_01_1k001.material} position={[-0.66, 0.74, 0.96]} scale={0.62} />
        <mesh castShadow receiveShadow geometry={nodes.bend1001.geometry} material={nodes.bend1001.material} position={[-0.78, 0.58, 0.46]} scale={0.01} />
        <mesh castShadow receiveShadow geometry={nodes.Drill_01_1k001.geometry} material={nodes.Drill_01_1k001.material} position={[-0.6, 0.78, 0.47]} rotation={[Math.PI / 2, 0, 0.61]} scale={1.29} />
        <mesh castShadow receiveShadow geometry={nodes.measuring_tape_01_1k001.geometry} material={nodes.measuring_tape_01_1k001.material} position={[-0.6, 0.75, 0.32]} scale={1.07} />
        <mesh castShadow receiveShadow geometry={nodes['tool-rack002'].geometry} material={nodes['tool-rack002'].material} position={[-0.92, 0.73, 0.29]} rotation={[0, Math.PI / 2, 0]} scale={0} />
        <mesh castShadow receiveShadow geometry={nodes.screwdriver002.geometry} material={nodes.screwdriver002.material} position={[-0.07, 0.62, 0.31]} rotation={[0, 1.16, 0]} scale={0} />
        <mesh castShadow receiveShadow geometry={nodes.screwdriver001.geometry} material={nodes.screwdriver001.material} position={[-0.89, 0.77, 0.3]} rotation={[0, Math.PI / 2, 0]} scale={0} />
        <mesh castShadow receiveShadow geometry={nodes.lampa.geometry} material={nodes.lampa.material} position={[-0.62, 0.74, -0.07]} rotation={[0, 1.12, 0]} scale={0.72} />
        <mesh castShadow receiveShadow geometry={nodes.steel_frame_shelves_01_1k.geometry} material={nodes.steel_frame_shelves_01_1k.material} position={[-0.79, 0.1, -0.55]} rotation={[0, Math.PI / 2, 0]} scale={0.74} />
        <mesh castShadow receiveShadow geometry={nodes.cardboard_box_01_1k.geometry} material={nodes.cardboard_box_01_1k.material} position={[-0.8, 0.58, -0.7]} scale={0.83} />
        <mesh castShadow receiveShadow geometry={nodes.lampa_perete.geometry} material={nodes.lampa_perete.material} position={[-0.27, 1.4, -0.87]} scale={0.01} />
        <mesh castShadow receiveShadow geometry={nodes.lampa_perete001.geometry} material={nodes.lampa_perete001.material} position={[0.43, 1.4, -0.87]} scale={0.01} />
        <mesh castShadow receiveShadow geometry={nodes.cardboard_box_01_1k001.geometry} material={nodes.cardboard_box_01_1k001.material} position={[-0.8, 0.2, -0.38]} scale={0.83} />
        <mesh castShadow receiveShadow geometry={nodes.cardboard_box_01_1k002.geometry} material={nodes.cardboard_box_01_1k002.material} position={[-0.8, 0.2, -0.78]} scale={0.83} />
        <mesh castShadow receiveShadow geometry={nodes.cardboard_box_01_1k003.geometry} material={nodes.cardboard_box_01_1k003.material} position={[-0.8, 1.33, -0.76]} scale={0.83} />
        <mesh castShadow receiveShadow geometry={nodes.canapea.geometry} material={nodes.canapea.material} position={[0.01, 0.12, -0.8]} scale={[0.02, 0.03, 0.02]} />
        <mesh castShadow receiveShadow geometry={nodes.katana.geometry} material={nodes.katana.material} position={[-0.74, 0.31, 0.25]} rotation={[1.65, -0.03, 0.33]} />
        <mesh castShadow receiveShadow geometry={nodes.desk.geometry} material={nodes.desk.material} position={[0.03, 0.44, 0.39]} rotation={[0, Math.PI / 2, 0]} scale={0.22} />
        <mesh castShadow receiveShadow geometry={nodes.desk001.geometry} material={nodes.desk001.material} position={[0.41, 0.44, 0.35]} rotation={[0, -Math.PI / 2, 0]} scale={0.22} />
        <mesh castShadow receiveShadow geometry={nodes.surusurubelnita002.geometry} material={nodes.surusurubelnita002.material} position={[-1.87, 0.11, 2.68]} rotation={[0, -0.59, Math.PI / 2]} scale={1.06} />
        <mesh castShadow receiveShadow geometry={nodes.steel_frame_shelves_01_1k001.geometry} material={nodes.steel_frame_shelves_01_1k001.material} position={[-2.65, 0.1, 1.47]} rotation={[0, 0.96, 0]} scale={0.74} />
        <mesh castShadow receiveShadow geometry={nodes.cardboard_box_01_1k005.geometry} material={nodes.cardboard_box_01_1k005.material} position={[-2.76, 0.2, 1.6]} rotation={[0, -0.61, 0]} scale={0.83} />
        <mesh castShadow receiveShadow geometry={nodes.cardboard_box_01_1k007.geometry} material={nodes.cardboard_box_01_1k007.material} position={[-2.54, 1.33, 1.29]} rotation={[0, -0.61, 0]} scale={0.83} />
        <mesh castShadow receiveShadow geometry={nodes.desk002.geometry} material={nodes.desk002.material} position={[-1.62, 0.44, 1.2]} rotation={[Math.PI, 0, Math.PI]} scale={0.22} />
        <mesh castShadow receiveShadow geometry={nodes.Drill_01_1k002.geometry} material={nodes.Drill_01_1k002.material} position={[-1.46, 0.62, 1.2]} rotation={[0, 0.42, -0.09]} scale={1.29} />
        <mesh castShadow receiveShadow geometry={nodes.bench_vice_01_1k002.geometry} material={nodes.bench_vice_01_1k002.material} position={[-2.64, 0.58, 1.57]} rotation={[0, -0.48, 0]} scale={0.62} />
        <mesh castShadow receiveShadow geometry={nodes.katana001.geometry} material={nodes.katana001.material} position={[-1.5, 0.13, 1.15]} rotation={[Math.PI / 2, 0, 1.32]} scale={[0.71, 0.83, 0.7]} />
        <mesh castShadow receiveShadow geometry={nodes.Cube002.geometry} material={nodes.Cube002.material} position={[-2.21, 0.13, 2.41]} rotation={[Math.PI / 2, 0, -0.21]} scale={0.46} />
        <mesh castShadow receiveShadow geometry={nodes.lampa_perete002.geometry} material={nodes.lampa_perete002.material} position={[-2.05, 1.4, 1.13]} scale={0.01} />
        <mesh castShadow receiveShadow geometry={nodes.lampa_perete003.geometry} material={nodes.lampa_perete003.material} position={[-1.27, 1.4, 1.13]} scale={0.01} />
        <mesh castShadow receiveShadow geometry={nodes.screwdriver003.geometry} material={nodes.screwdriver003.material} position={[-1.16, 0.11, 2.2]} rotation={[0, 1.16, 0]} scale={0} />
        <mesh castShadow receiveShadow geometry={nodes.bend1002.geometry} material={nodes.bend1002.material} position={[1.23, 0.58, -1.55]} scale={0.01} />
        <mesh castShadow receiveShadow geometry={nodes.steel_frame_shelves_01_1k002.geometry} material={nodes.steel_frame_shelves_01_1k002.material} position={[1.44, 0.1, -2.37]} scale={0.74} />
        <mesh castShadow receiveShadow geometry={nodes.lampa_perete004.geometry} material={nodes.lampa_perete004.material} position={[1.13, 1.4, -1.65]} rotation={[0, Math.PI / 2, 0]} scale={0.01} />
        <mesh castShadow receiveShadow geometry={nodes.lampa_perete005.geometry} material={nodes.lampa_perete005.material} position={[2.45, 1.4, -2.86]} scale={0.01} />
        <mesh castShadow receiveShadow geometry={nodes.katana002.geometry} material={nodes.katana002.material} position={[1.05, 0.31, -2.13]} rotation={[0, 1.27, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.desk003.geometry} material={nodes.desk003.material} position={[2.18, 0.44, -1.5]} rotation={[0, Math.PI / 2, 0]} scale={0.22} />
        <mesh castShadow receiveShadow geometry={nodes.desk004.geometry} material={nodes.desk004.material} position={[2.56, 0.44, -1.54]} rotation={[0, -Math.PI / 2, 0]} scale={0.22} />
        <mesh castShadow receiveShadow geometry={nodes.Drill_01_1k003.geometry} material={nodes.Drill_01_1k003.material} position={[2.06, 0.61, -1.23]} rotation={[Math.PI, 1.21, 3.06]} scale={1.29} />
        <mesh castShadow receiveShadow geometry={nodes.screwdriver004.geometry} material={nodes.screwdriver004.material} position={[2.57, 0.62, -1.2]} rotation={[0, 1.16, 0]} scale={0} />
        <mesh castShadow receiveShadow geometry={nodes.screwdriver005.geometry} material={nodes.screwdriver005.material} position={[2.27, 0.62, -1.2]} rotation={[0, -1.25, 0]} scale={0} />
        <mesh castShadow receiveShadow geometry={nodes.bench_vice_01_1k003.geometry} material={nodes.bench_vice_01_1k003.material} position={[1.34, 0.74, -1.11]} scale={0.62} />
        <mesh castShadow receiveShadow geometry={nodes.cardboard_box_01_1k004.geometry} material={nodes.cardboard_box_01_1k004.material} position={[1.2, 1.33, -2.4]} scale={0.83} />
        <mesh castShadow receiveShadow geometry={nodes.surusurubelnita003.geometry} material={nodes.surusurubelnita003.material} position={[1.08, 0.89, -1.14]} rotation={[Math.PI / 2, 1.19, 0]} scale={0.83} />
        <mesh castShadow receiveShadow geometry={nodes.surusurubelnita004.geometry} material={nodes.surusurubelnita004.material} position={[1.08, 0.89, -1.14]} rotation={[Math.PI / 2, 1.19, 0]} scale={0.83} />
        <mesh castShadow receiveShadow geometry={nodes.screwdriver006.geometry} material={nodes.screwdriver006.material} position={[1.08, 1.02, -1.17]} rotation={[0, Math.PI / 2, 0]} scale={0} />
        <mesh castShadow receiveShadow geometry={nodes.desk005.geometry} material={nodes.desk005.material} position={[0.54, 2.33, -2.79]} rotation={[Math.PI, 0, Math.PI]} scale={0.22} />
        <mesh castShadow receiveShadow geometry={nodes.desk006.geometry} material={nodes.desk006.material} position={[-0.34, 2.33, -2.79]} rotation={[Math.PI, 0, Math.PI]} scale={0.22} />
        <mesh castShadow receiveShadow geometry={nodes.steel_frame_shelves_01_1k003.geometry} material={nodes.steel_frame_shelves_01_1k003.material} position={[-0.77, 1.99, -1.61]} rotation={[0, Math.PI / 2, 0]} scale={0.74} />
        <mesh castShadow receiveShadow geometry={nodes.cardboard_box_01_1k006.geometry} material={nodes.cardboard_box_01_1k006.material} position={[-0.79, 3.22, -1.37]} rotation={[-Math.PI, 1.54, -Math.PI]} scale={0.83} />
        <mesh castShadow receiveShadow geometry={nodes.lampa_perete006.geometry} material={nodes.lampa_perete006.material} position={[-0.22, 3.52, -2.86]} scale={0.01} />
        <mesh castShadow receiveShadow geometry={nodes.lampa_perete007.geometry} material={nodes.lampa_perete007.material} position={[0.47, 3.52, -2.86]} scale={0.01} />
        <mesh castShadow receiveShadow geometry={nodes.katana003.geometry} material={nodes.katana003.material} position={[-0.89, 2.69, -2.95]} rotation={[3.03, 0, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.bench_vice_01_1k004.geometry} material={nodes.bench_vice_01_1k004.material} position={[-0.68, 2.47, -1.36]} rotation={[0, 1.31, 0]} scale={0.62} />
        <mesh castShadow receiveShadow geometry={nodes.screwdriver007.geometry} material={nodes.screwdriver007.material} position={[0.08, 2.52, -1.47]} rotation={[0, -1.25, 0]} scale={0} />
        <mesh castShadow receiveShadow geometry={nodes.screwdriver008.geometry} material={nodes.screwdriver008.material} position={[0.14, 2.52, -1.58]} rotation={[-Math.PI, 0.51, -Math.PI]} scale={0} />
        <mesh castShadow receiveShadow geometry={nodes.screwdriver009.geometry} material={nodes.screwdriver009.material} position={[0.2, 2.52, -1.64]} rotation={[-Math.PI, 1.45, -Math.PI]} scale={0} />
        <mesh castShadow receiveShadow geometry={nodes.lampa_perete008.geometry} material={nodes.lampa_perete008.material} position={[-2.22, 3.52, -0.86]} scale={0.01} />
        <mesh castShadow receiveShadow geometry={nodes.lampa_perete009.geometry} material={nodes.lampa_perete009.material} position={[-1.53, 3.52, -0.86]} scale={0.01} />
        <mesh castShadow receiveShadow geometry={nodes.desk007.geometry} material={nodes.desk007.material} position={[-1.35, 2.33, -0.81]} rotation={[Math.PI, 0, Math.PI]} scale={[0.17, 0.22, 0.22]} />
        <mesh castShadow receiveShadow geometry={nodes.desk008.geometry} material={nodes.desk008.material} position={[-2.14, 2.33, -0.81]} rotation={[Math.PI, 0, Math.PI]} scale={0.22} />
        <mesh castShadow receiveShadow geometry={nodes.cardboard_box_01_1k008.geometry} material={nodes.cardboard_box_01_1k008.material} position={[-1.36, 2.01, -0.79]} rotation={[-Math.PI, 1.54, -Math.PI]} scale={0.83} />
        <mesh castShadow receiveShadow geometry={nodes.Drill_01_1k004.geometry} material={nodes.Drill_01_1k004.material} position={[-1.78, 2.52, 0.35]} rotation={[0, 1.41, -0.09]} scale={1.29} />
        <mesh castShadow receiveShadow geometry={nodes.katana004.geometry} material={nodes.katana004.material} position={[-2.24, 2.69, -0.84]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={-0.35} />
      </group>
    </group>
  )
}

useGLTF.preload('/display2.gltf')
